---
# TODO: description
# TODO: link
id: "wikicite_now_2018"
name: "WikiCite NoW 2018"
lang: en
disabled: False
description: "A project to improve Wikipedia's coverage of newspapers."
contacts:
  - "User:Peteforsyth"
wikiproject_name: "WikiProject_Newspapers"
campaign_start_date: 2018-06-01
campaign_end_date: 2018-12-15
date_created: 2018-11-29
article_list:
  # defaults to article_list.yaml, this is from sparql json output
  type: "sparql_json_file"
  path: "query_selma.json"
  title_key: "page_titleEN"
fetch_frequency: 1h  # format: 1d 2h 3.5m 0s, parsed by timeutils.parse_timedelta
save_frequency: 2h
goals:
  - name: "Has Newspaper Infobox"
    desc: "Get exactly one newspaper or magazine infobox on every article"
    metric: template_count
    metric_args:
      template_name: Infobox Newspaper
      case_sensitive: False
    target:
      value: 1
      cmp: eq  # gt, ge, lt, le, eq, ne, bool  (default ge)
      ratio: 1.0  # 100% coverage
      # total: 500  # 500 articles, mutually exclusive with above
  - name: "In Wikiproject Newspapers"
    metric: in_wikiproject
    metric_args:
      wikiproject: Newspapers
      case_sensitive: False
    target:
      value: 1
      cmp: bool
  - name: "In Wikiproject Journalism"
    metric: in_wikiproject
    metric_args:
      wikiproject: Journalism
      case_sensitive: False
    target:
      value: 1
      cmp: bool
  - name: "Citation count"
    metric: ref_count
    target:
      value: 10
      ratio: 1.0
  - name: "Exists on Wikidata"
    metric: wikidata_item
    target:
      value: 1
      cmp: eq
      ratio: 1.0
  # may be example of campaign-wide/project-wide/set-wide goal (aggregated, not per article)
  # - metric: overall_article_count
  #   name: "Overall Article Count"
  #   target:
  #     # one of the following
  #     delta: 200  # 200 more articles
  #     delta_relative: 1.2  # 20% more articles than the start
  #     total: 2000  # 2000 total articles

...
